version: "3.8"

services:
  reverse-proxy:
    image: "traefik:v2.3"
    restart: always
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_API_EMAIL
      - CF_DNS_API_TOKEN
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  postgres:    
    image: postgres:13.1
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD

  api:     
    environment: 
      - ConnectionStrings__DefaultConnection
    restart: always
    depends_on:
      - reverse-proxy
      - postgres
    build:
      context: ./TodoApi
      dockerfile: Api.Dockerfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`todo-api.davidmannes.de`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
